---
title: "T Distribution"
author: "Jack Hester"
date: "12/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=F, results='hide', echo=F}
source("colors.R")
source("plot-themes.R")
source("animation-engine.R")
source("frame-builder.R")
library(sys)
library(ggplot2)
library(gganimate)
library(av)
library(gifski)
library(png)
library(animation)
library(purrr)
library(magick)
library(rlist)
theme <- set.ggplot.colorscheme("dark", FALSE) # color scheme via plot-themes.R
```

# t distribution code 

### Code is used for Education Cafe and the Brown University CEPC 0904 course.

```{r visualizing the t distribution}
x <- seq(-4, 4, length=1000) # set range and how many points to evaluate at (more=smoother line)
hx <- dnorm(x)

degf <- c(1, 3, 8, 30)
colors <- c(YELLOW, ORANGE, BLUE, RED, WHITE)
labels <- c("df=1", "df=3", "df=8", "df=30", "normal")

# create plot, plot std norm dist
set.plot.colorscheme('dark') # set par
plot(x, dnorm(x), type="l", lty=2, xlab="x value", # dnorm is for normal dist
  ylab="Density", main="Comparison of t and Normal Distributions", col="white")
abline(v=0)

# plot t dist
for (i in 1:4){
  lines(x, dt(x,degf[i]), lwd=2, col=colors[i]) #dt is for t dist
}

legend("topright", inset=.05, title="Distributions",
  labels, lwd=2, lty=c(1, 1, 1, 1, 2), col=colors)
```

If you were to 
##Comparing the results to the t test command

```{r t_test}
#t.test()
```


```{r DELETE THIS}

library(gapminder)

p <- ggplot(
  airquality,
  aes(Day, Temp, group = Month, color = factor(Month))
  ) +
  geom_line(size=2) +
  scale_color_viridis_d() +
  labs(x = "Day of Month", y = "Temperature") +
  theme + transition_reveal(Day)
#p
#p
animate.and.save.ggplot(p, "D:\\math_animations\\R_tests\\norm_test.gif")
# TODO: make the size of axes and legend bigger
```

```{r}
# fill hists and barplots
x <- rnorm(10000)
v <- data.frame(x)
list.of.plots <- list()
list.of.plots.pdf <- list()
# normal pdf for comparison
norm.pdf <- data.frame(dnorm(seq(-4,4,length=10000)))
colnames(norm.pdf) <- c('x')
bw <- 0.2 # bin width
#ggplot(norm.pdf, aes(x=x)) + geom_line()
#ggplot(data=data.frame(x=c(-4,4)), aes(x)) + stat_function(fun=dnorm, n=101) + scale_c
len <- length(v[,1])
#print(len)
for(i in 1:len){
  curr.hist.range <- data.frame(v[1:i,])
  #curr.hist.range <- data.frame(v[1:i,])
  colnames(curr.hist.range) <- c('x')
  #colnames(curr.hist.range) <- c('x')
  # raw number
  m <- ggplot(curr.hist.range, aes(x=x)) + geom_histogram(binwidth=0.2) + xlim(-4, 4) + theme
  list.of.plots[[i]] <- m
  # PDF
  # multiplying by the bin width works to make all of the bars equal a total height of 1, but not the area under the curve equaling one
  adj <-bw*index
  #print(adj)
  n <- ggplot(data=data.frame(x=c(-4,4)), aes(x)) + geom_histogram(data=curr.hist.range, aes(x=x,y=..density..), binwidth=bw) + stat_function(fun=dnorm, n=101, color=RED, size=1.5) +  xlim(-4, 4) +  theme #+ scale_y_continuous()
  list.of.plots.pdf[[i]] <- n
}
#list.of.plots.pdf[9000]
#n <- ggplot(curr.hist.range, aes(x=x,y=..density..)) + geom_histogram(binwidth=0.2) + xlim(-4, 4) +  theme
#TODO: make this barpot so it will show density (out of current number of points)

#generatePNGs(list.of.plots, "D:\\math_animations\\R_tests\\normal_pngs")
#pngs.to.gif(imgpath="D:\\math_animations\\R_tests\\normal_pngs", savename="D:\\math_animations\\R_tests\\hist.gif")

#source('frame-builder.R')
#TODO: fix the density to make it out of the normal with 0.4 max (divide by total num?)
#generatePNGs(list.of.plots.pdf, "D:\\math_animations\\R_tests\\norm_pdf_pngs")
generatePNGs(list.of.plots.pdf, "/Users/jack/Desktop/imgs")

#pngs.to.mp4(imgpath="D:\\math_animations\\R_tests\\normal_pngs", savename="D:\\math_animations\\R_tests\\hist_mp4.mp4")

#pngs_to_mp4(imgpath="D:\\math_animations\\R_tests\\normal_pngs", savename="D:\\math_animations\\R_tests\\hist_mp4.mp4", frame.rate=10)


pngs_to_gif(imgpath="D:\\math_animations\\R_tests\\norm_pdf_pngs", savename="D:\\math_animations\\R_tests\\norm_pdf_gif.gif", frame.rate=10)

source('animation-engine.R')
pngs_to_mp4(imgpath="D:\\math_animations\\R_tests\\norm_pdf_pngs", savename="D:\\math_animations\\R_tests\\norm_pdf_mp4.mp4", frame.rate=10)

pngs_to_gif(imgpath="D:\\math_animations\\R_tests\\normal_pngs", savename="D:\\math_animations\\R_tests\\hist_pdf_mp4.gif", frame.rate=10)

pngs_to_hq_gif(imgpath="D:\\math_animations\\R_tests\\normal_pngs", savename="D:\\math_animations\\R_tests\\hist_gif_hq.gif", fps_val=10)
```


